package de.ftes.hpi.nlp.languagemodel;

public interface LanguageModel {
	/**
	 * Calculate the probability of the sentence being generated by the language model.
	 * Return the logarithm of the probability to avoid underflow errors.
	 * @param sentence
	 * @return
	 */
	double sentenceProbabilityLogarithm(Sentence sentence);
}
